### ISSUE TITLE
extracting a single point

### ISSUE THREAD

**Issue by matteodefelice** [hypertidy/tidync#53]
What if I want to extract a time-series, i.e. the data in a specific grid point? Should I filter using `lat == X, lon == Y`? What if I don't know the *exact* coordinates but I want to get the closest? I see it's a trivial problem, but I just want to know what you'd suggest.

**Comment by mdsumner** [comment]
This is a very good question ;)  and it's something I worried about quite a bit at the beginning. 

You might already know this, but you can use the special name "index" which is defined for any axis

`lat = index < 10` 

and that really can be used for exact comparisons, because it will always be an integer (1:length(lat)). 

`lat = index == 10` 

for example, where index is literally the step position along that axis. We can use this to avoid inequalities  to find which provides the smallest difference: 

`lat = index == which.min(abs(lat - 11.34))`

You definitely should be wary of `lat == X` type tests. I need to consider if these kinds of expressions can be assessed for whether it's appropriate to do a particular kind of comparison, but I've also experimented with creating *custom variables on each axis* for nuanced slicing. 

Also note that other expression might be sparse, but tidync currently has to keep the entire contiguous subset for a full slice index. 

`lat = index %in% c(2, 5, 7, 9)`

that would be forced to include all of `2:9`. 

This is related to polygon or line overlay, which provides a "grouping" of cells, rather than rectangular slicing - I haven't though deeply about whether there's more common ground here, so any input is welcome!

**Comment by matteodefelice** [comment]
Great! I think that `index` is exactly what I was looking for.
> `lat = index == which.min(abs(lat - 11.34))`

this one is the answer, thank you!
