### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by rmendels** [hypertidy/tidync#73]
As best as I can tell,  slicing in coordinate space requires that the bounds on the slice be on the coordinate grid.  What would be nice is if the program would take the requested coordinate limits,  and if not on the grid,  convert by some rule  (closest grid point or smallest limits that include the range requested) and do the slice.  That way if a user wanted the data from say a latitude of (35, 40) they don't have to find out the exact coordinate system in the file,  but will get back a consistent set of results.

ERDDAP for instance finds the closest grid point to the requested max and min grid points,  but it might make just as much sense to find the smallest region that includes the requested range.

**Comment by mdsumner** [comment]
Do you mean so that a min/max is within the interval of a cell, not literally greater or less than a given grid point? I think that's pretty darn tricky, but could be done with a reasonable default (like raster::crop(, snap = "out") which, I think, should be raster's default). It's hard because ranges are literally ambiguous in NetCDF, if a rectilinear axis doesn't also have a min/max then the size of the first and last interval width is unclear, and those min/max don't semantically map to the model anyway, it just becomes an ad hoc coding thing. 

Otherwise I'm not sure I understand the request?

**Comment by rmendels** [comment]
Suppose I have latitudes (and this is from an actual file - a GHRSST file)
(38.97917, 39.02083, 39.0625, 39.10417, 39.14583, 39.1875, 39.22917, 39.27083, 39.3125, 39.35417, 39.39583, 39.4375, 39.47917, 39.52083, 39.5625, 39.60417, 39.64583, 39.6875, 39.72917, 39.77083, 39.8125, 39.85417, 39.89583, 39.9375, 39.97917, 40.02083, 40.0625, 40.10417, 40.14583, 40.1875, 40.22917, 40.27083, 40.3125, 40.35417, 40.39583, 40.4375, 40.47917, 40.52083, 40.5625, 40.60417, 40.64583, 40.6875, 40.72917, 40.77083, 40.8125, 40.85417, 40.89583, 40.9375, 40.97917, 41.02083) 

and longitudes 
(176.9792, 177.0208, 177.0625, 177.1042, 177.1458, 177.1875, 177.2292, 177.2708, 177.3125, 177.3542, 177.3958, 177.4375, 177.4792, 177.5208, 177.5625, 177.6042, 177.6458, 177.6875, 177.7292, 177.7708, 177.8125, 177.8542, 177.8958, 177.9375, 177.9792, 178.0208, 178.0625, 178.1042, 178.1458, 178.1875, 178.2292, 178.2708, 178.3125, 178.3542, 178.3958, 178.4375, 178.4792, 178.5208,  178.5625, 178.6042, 178.6458, 178.6875, 178.7292, 178.7708, 178.8125, 178.8542, 178.8958, 178.9375, 178.9792, 179.0208, 179.0625, 179.1042,  179.1458, 179.1875, 179.2292, 179.2708, 179.3125, 179.3542, 179.3958,  179.4375, 179.4792, 179.5208, 179.5625, 179.6042, 179.6458, 179.6875,179.7292, 179.7708, 179.8125, 179.8542, 179.8958, 179.9375, 179.9792)

so as a user, I want any data with latitudes between (39, 41) and longitudes between (178, 179).  So if I give you that bounding box as the request,  I would get all values on latitudes:

39.02083, 39.0625, 39.10417, 39.14583, 39.1875, 39.22917, 39.27083, 39.3125, 39.35417, 39.39583, 39.4375, 39.47917, 39.52083, 39.5625, 39.60417, 39.64583, 39.6875, 39.72917, 39.77083, 39.8125, 39.85417, 39.89583, 39.9375, 39.97917, 40.02083, 40.0625, 40.10417, 40.14583, 40.1875, 40.22917, 40.27083, 40.3125, 40.35417, 40.39583, 40.4375, 40.47917, 40.52083, 40.5625, 40.60417, 40.64583, 40.6875, 40.72917, 40.77083, 40.8125, 40.85417, 40.89583, 40.9375, 40.97917

and longitudes
178.0208, 178.0625, 178.1042, 178.1458, 178.1875, 178.2292, 178.2708, 178.3125, 178.3542, 178.3958, 178.4375, 178.4792, 178.5208,  178.5625, 178.6042, 178.6458, 178.6875, 178.7292, 178.7708, 178.8125, 178.8542, 178.8958, 178.9375, 178.9792

otherwise as I a user I would have o find the limits that met my criteria but were actually on the grid.

**Comment by mdsumner** [comment]
Cool, thanks - understood!  I'd definitely call that "inclusive interval" or something, it's exactly what raster means by `snap = "out"`. 

There's no way to do it "natively" with dplyr expressions, because they are arbitrary on row values - not inherent to a sequence of values, and tidync just passes those user expressions directly: 

https://github.com/hypertidy/tidync/blob/master/R/hyper_filter.R#L48

But, the "transforms tables" - the tables that store the axis coordinate sequeneces and their `select` flag could be checked afterwards for this inclusivity - except that all we have are these bare dplyr expressions. 

So - I think this has to be a new function that takes ranges for each axis and applies the less general comparisons directly. I'll put this together, thanks!

**Comment by mdsumner** [comment]
How do you envisage the interface? I was thinking something like this, so for a 2D array with longitude/latitude in that order you'd need

```R
hyper_ranger(x, c (178, 179), c(39, 41))
```

and if it was 3D (degenerate or not) you could leave the 3rd index open (keep all) with an open NA (or NULL maybe)


```R
hyper_ranger(x, c (178, 179), c(39, 41), NA)
```

But I'm otherwise lost with how this would be used. It would be annoying to have to fill every slot, though maybe you could have special functions `first()` `second` `third` etc. and do this? 

```R
hyper_ranger(x, first(178, 179), second(39, 41))
```

How does xarray do this?  (I'll eventually have a look but if anyone already knows I'm open to ideas for the user-code).

**Comment by rmendels** [comment]
how array does indexing:

http://xarray.pydata.org/en/stable/indexing.html

**Comment by rmendels** [comment]
clearly that should have been "how xarray does indexing" but i always get tripped by autocorrect.  I know a lot of people really like how xarray handles things.  what I don't know is what it does if a request does not have the limits on an actual grid point.  Treating that case is not that difficult - you just decide what rule you want to use - for ERDDAP say,  given the bounding values for each dimension,  find the actual grid points closest to the min_value and to the max_value and use that as the limits of the request. But  I think you can use any rule as long as it is consistent and clearly stated  (as a said,  another possible rule is given the requested values,  find the actual grid points with the smallest range that completely enclose the requested points,  and then use that as the request).

**Comment by rmendels** [comment]
Okay I just answered my own question:
```python
import xarray as xr
import numpy as np
import pandas as pd
da = xr.DataArray(np.random.rand(4, 3), [('time', pd.date_range('2000-01-01T12:00', periods=4)), ('space', ['IA', 'IL', 'IN'])])
ds = da.to_dataset(name='foo')
ds
<xarray.Dataset>
Dimensions:  (space: 3, time: 4)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01T12:00:00 2000-01-02T12:00:00 ...
  * space    (space) <U2 'IA' 'IL' 'IN'
Data variables:
    foo      (time, space) float64 0.2523 0.4815 0.9982 0.4701 0.4178 0.6565 ...

ds.loc[dict(time='2000-01-01T12:00')]
<xarray.Dataset>
Dimensions:  (space: 3)
Coordinates:
    time     datetime64[ns] 2000-01-01T12:00:00
  * space    (space) <U2 'IA' 'IL' 'IN'
Data variables:
    foo      (space) float64 0.2523 0.4815 0.9982
ds.loc[dict(time='2000-01-01')]
<xarray.Dataset>
Dimensions:  (space: 3, time: 1)
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01T12:00:00
  * space    (space) <U2 'IA' 'IL' 'IN'
Data variables:
    foo      (time, space) float64 0.2523 0.4815 0.9982
```
So it allowed me to give a time value not one of the actual times and it returned a subset.  I don't know the rule they use but you might ask someone like Ryan Abernathey

**Comment by rmendels** [comment]
Just played with it some more.  Not as robust as I would have hoped.  If instead I do:

```python
ds.loc[dict(time='2000-01-01T09:00')]
```
`xarray` throws an error.  What I am after is that these are often used by relatively inexperienced programmers.  They don't want to have to find the actual coordinate values.  They want to say:  give me all the data that are within latitude bounds (30, 35) and longitude bounds (-120, -115) even if none of those four numbers is an actual grid point.

**Comment by rmendels** [comment]
okay my lack of knowledge of `xarray` is showing (I use `netcdf4`).  `xarray` does do what I want if done properly:

```python
import xarray as xr
import numpy as np
import pandas as pd
da = xr.DataArray(np.random.rand(4, 3), [('time', pd.date_range('2000-01-01T12:00', periods=4)), ('space', ['IA', 'IL', 'IN'])])
da
<xarray.DataArray (time: 4, space: 3)>
array([[0.740246, 0.9931  , 0.784128],
       [0.007933, 0.327255, 0.841473],
       [0.171023, 0.239136, 0.483274],
       [0.541009, 0.52966 , 0.653923]])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01T12:00:00 2000-01-02T12:00:00 ...
  * space    (space) <U2 'IA' 'IL' 'IN'

 da.loc['2000-01-01':'2000-01-03', 'IA']
<xarray.DataArray (time: 3)>
array([0.740246, 0.007933, 0.171023])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01T12:00:00 2000-01-02T12:00:00 ...
    space    <U2 'IA'

da.loc['2000-01-01 09:00':'2000-01-03 09:00', 'IA']
<xarray.DataArray (time: 2)>
array([0.69457 , 0.382959])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-01T12:00:00 2000-01-02T12:00:00
    space    <U2 'IA'

da.loc['2000-01-01 14:00':'2000-01-03 09:00', 'IA']
<xarray.DataArray (time: 1)>
array([0.382959])
Coordinates:
  * time     (time) datetime64[ns] 2000-01-02T12:00:00
    space    <U2 'IA'
```

**Comment by mdsumner** [comment]
This is really usefull, thanks!  I
